server:
  port: 8080

spring:
  application:
    name: tcm-backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tcm}
    username: ${DB_USERNAME:tcm}
    password: ${DB_PASSWORD:changeme}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
